# Generated by Django 5.1 on 2025-04-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='impositivo',
            field=models.CharField(choices=[('RI', 'Responsable Inscripto'), ('E', 'Exento'), ('C', 'Consumidor Final'), ('M', 'Responsable Monotributo+')], default='RI', max_length=5),
        ),
    ]
